[package]
name = "rusty-adr"
version = "0.1.0"
authors = ["Alec Savoy <alecjsavvy@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.8.0", features = [ "attributes" ] }
mdbook = "0.4.4"
